
import { Project, Phase, Artifact, TaskStatus } from './types';

export function generateArtifact(project: Project, phase: Phase): Artifact {
    return {
        id: `art_gen_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        projectId: project.id,
        phaseId: phase.id,
        version: 1,
        filename: `${phase.phaseTitle.replace(/\s+/g, '_')}_Output.md`,
        format: 'md',
        content: `# ${phase.phaseTitle}\n\nGenerated content for ${project.name}.\n\nGoal: ${project.goal}\n\nThis is a placeholder artifact generated by the Quick Generate action.`,
        createdAt: Date.now(),
        qaStatus: 'pending'
    };
}
